# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

# Define the number of master and worker nodes
# If this number is changed, remember to update setup-hosts.sh script with the new hosts IP details in /etc/hosts of each VM.
NUM_MASTER_NODE = 2
NUM_WORKER_NODE = 2

IP_NW = "172.16.19.2"
MASTER_IP_START = 10
WORKER_IP_START = 20
LB_IP_START = 30

# These MAC Addresses were generated at https://www.hellion.org.uk/cgi-bin/randmac.pl?scope=local&type=unicast
# They were then mapped on the router the ip addresses listed. So in case you use these in my network
# you will be in trouble. Generate your own and talk to me about the router config.
MASTER_MACS = ["22AD6F387AE3", "AAA8A3966ABB"]
WORKER_MACS = ["56E2F8101C22", "C6F9ED5BB3EA"]
LB_MAC = "165898F98292"


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.box = "base"
  config.vm.box = "ubuntu/bionic64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
  
  if ENV["K8S_TYPE"] == "MASTER"
    puts "Do Masters"
    setup_master_nodes(config)
  elsif ENV["K8S_TYPE"] == "WORKER"
    puts "Do Workers"
    setup_worker_nodes(config)
  elsif ENV["K8S_TYPE"] == "LB"
    puts "Do LB"
    setup_lb_node(config)
  else
    puts "Provide one of MASTER, WORKER, LB in the K8S_TYPE environment variable."
    exit
  end
  # exit

end

def setup_worker_nodes(config)
 # Provision Worker Nodes
 (1..NUM_WORKER_NODE).each do |i|
  config.vm.define "worker-#{i}" do |node|
      node.vm.provider "virtualbox" do |vb|
          vb.name = "kubernetes-ha-worker-#{i}"
          vb.memory = 512
          vb.cpus = 1
      end
      node.vm.hostname = "worker-#{i}"
      # node.vm.network :private_network, ip: IP_NW + "#{WORKER_IP_START + i}"
      node.vm.network :public_network, :mac => WORKER_MACS[i - 1], use_dhcp_assigned_default_route: true, :ip => IP_NW + "#{WORKER_IP_START + i - 1}"
      # node.vm.network :public_network, :mac => WORKER_MACS[i - 1], :ip => IP_NW + "#{WORKER_IP_START + i - 1}"
  # node.vm.network "forwarded_port", guest: 22, host: "#{2720 + i}"

      node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh" do |s|
        s.args = ["enp0s8"]
      end

      node.vm.provision "setup-dns", type: "shell", :path => "ubuntu/update-dns.sh"
      node.vm.provision "install-docker", type: "shell", :path => "ubuntu/install-docker.sh"
      node.vm.provision "allow-bridge-nf-traffic", :type => "shell", :path => "ubuntu/allow-bridge-nf-traffic.sh"

  end
end
end


def setup_lb_node(config)
  # Provision Load Balancer Node
  config.vm.define "loadbalancer" do |node|
    node.vm.provider "virtualbox" do |vb|
        vb.name = "kubernetes-ha-lb"
        vb.memory = 512
        vb.cpus = 1
    end
    node.vm.hostname = "loadbalancer"
    # node.vm.network :private_network, ip: IP_NW + "#{LB_IP_START}"
    node.vm.network :public_network, :mac => LB_MAC, use_dhcp_assigned_default_route: true, :ip => IP_NW + "#{LB_IP_START}"
    # node.vm.network :public_network, :mac => LB_MAC
  	# node.vm.network "forwarded_port", guest: 22, host: 2730

    node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh" do |s|
      s.args = ["enp0s8"]
    end

    node.vm.provision "setup-dns", type: "shell", :path => "ubuntu/update-dns.sh"

  end

end


def setup_master_nodes(config)
  puts "Provisioning Master Nodes"
  (1..NUM_MASTER_NODE).each do |i|
      config.vm.define "master-#{i}" do |node|
        # Name shown in the GUI
        node.vm.provider "virtualbox" do |vb|
            vb.name = "kubernetes-ha-master-#{i}"
            vb.memory = 2048
            vb.cpus = 2
        end
        node.vm.hostname = "master-#{i}"
        # node.vm.network :private_network, ip: IP_NW + "#{MASTER_IP_START + i}"
        node.vm.network :public_network, :mac => MASTER_MACS[i - 1], use_dhcp_assigned_default_route: true, :ip => IP_NW + "#{MASTER_IP_START + i - 1}"
        # node.vm.network :public_network, :mac => MASTER_MACS[i - 1], use_dhcp_assigned_default_route: true
        # node.vm.network "forwarded_port", guest: 22, host: "#{2710 + i}"

        node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh" do |s|
          s.args = ["enp0s8"]
        end

        node.vm.provision "setup-dns", type: "shell", :path => "ubuntu/update-dns.sh"

      end
  end
end

module OS
    def OS.windows?
        (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    end

    def OS.mac?
        (/darwin/ =~ RUBY_PLATFORM) != nil
    end

    def OS.unix?
        !OS.windows?
    end

    def OS.linux?
        OS.unix? and not OS.mac?
    end
end
